greybook/blueprints/admin.py
from flask import Blueprint, abort, current_app, flash, redirect, render_template, request, url_for
from flask_ckeditor import upload_fail, upload_success
from flask_login import current_user, login_required
from sqlalchemy import select

from greybook.core.extensions import db
from greybook.forms import EditCategoryForm, LinkForm, NewCategoryForm, PostForm, SettingForm
from greybook.models import Category, Comment, Link, Post
from greybook.utils import allowed_file, random_filename, redirect_back

admin_bp = Blueprint('admin', __name__)


@admin_bp.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    form = SettingForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.blog_title = form.blog_title.data
        current_user.blog_sub_title = form.blog_sub_title.data
        current_user.about = form.about.data
        current_user.custom_footer = form.custom_footer.data
        current_user.custom_css = form.custom_css.data
        current_user.custom_js = form.custom_js.data
        db.session.commit()
        flash('Setting updated.', 'success')
        return redirect(url_for('blog.index'))
    if request.method == 'GET':
        form.name.data = current_user.name
        form.blog_title.data = current_user.blog_title
        form.blog_sub_title.data = current_user.blog_sub_title
        form.about.data = current_user.about
        form.custom_footer.data = current_user.custom_footer
        form.custom_css.data = current_user.custom_css
        form.custom_js.data = current_user.custom_js
    return render_template('admin/settings.html', form=form)


@admin_bp.route('/post/manage')
@login_required
def manage_post():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['GREYBOOK_MANAGE_POST_PER_PAGE']
    stmt = select(Post).order_by(Post.created_at.desc())
    pagination = db.paginate(
        stmt,
        page=page,
        per_page=per_page,
        error_out=False,
    )
    if page > pagination.pages:
        return redirect(url_for('.manage_post', page=pagination.pages))
    posts = pagination.items
    return render_template('admin/manage_post.html', page=page, pagination=pagination, posts=posts)


@admin_bp.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        body = form.body.data
        category_id = form.category.data
        post = Post(title=title, body=body, category_id=category_id)
        db.session.add(post)
        db.session.commit()
        flash('Post created.', 'success')
        return redirect(url_for('blog.show_post', post_id=post.id))
    return render_template('admin/new_post.html', form=form)


@admin_bp.route('/post/<int:post_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_post(post_id):
    form = PostForm()
    post = db.session.get(Post, post_id) or abort(404)
    if form.validate_on_submit():
        post.title = form.title.data
        post.body = form.body.data
        post.category_id = form.category.data
        db.session.commit()
        flash('Post updated.', 'success')
        return redirect(url_for('blog.show_post', post_id=post.id))
    if request.method == 'GET':
        form.title.data = post.title
        form.body.data = post.body
        form.category.data = post.category_id
    return render_template('admin/edit_post.html', form=form)


@admin_bp.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = db.session.get(Post, post_id) or abort(404)
    post.delete()
    flash('Post deleted.', 'success')
    return redirect_back()


@admin_bp.route('/post/<int:post_id>/set-comment', methods=['POST'])
@login_required
def set_comment(post_id):
    post = db.session.get(Post, post_id) or abort(404)
    if post.can_comment:
        post.can_comment = False
        flash('Comment disabled.', 'success')
    else:
        post.can_comment = True
        flash('Comment enabled.', 'success')
    db.session.commit()
    return redirect_back()


@admin_bp.route('/comment/manage')
@login_required
def manage_comment():
    filter_rule = request.args.get('filter', 'all')  # 'all', 'unread', 'admin'
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['GREYBOOK_COMMENT_PER_PAGE']

    if filter_rule == 'unread':
        filtered_comments = select(Comment).filter_by(reviewed=False)
    elif filter_rule == 'admin':
        filtered_comments = select(Comment).filter_by(from_admin=True)
    else:
        filtered_comments = select(Comment)

    stmt = filtered_comments.order_by(Comment.created_at.desc())
    pagination = db.paginate(
        stmt,
        page=page,
        per_page=per_page,
        error_out=False,
    )
    if page > pagination.pages:
        return redirect(url_for('.manage_comment', page=pagination.pages, filter=filter_rule))
    comments = pagination.items
    return render_template('admin/manage_comment.html', comments=comments, pagination=pagination)


@admin_bp.route('/comment/<int:comment_id>/approve', methods=['POST'])
@login_required
def approve_comment(comment_id):
    comment = db.session.get(Comment, comment_id) or abort(404)
    comment.reviewed = True
    db.session.commit()
    flash('Comment published.', 'success')
    return redirect_back()


@admin_bp.route('/comments/approve', methods=['POST'])
@login_required
def approve_all_comment():
    stmt = select(Comment).filter_by(reviewed=False)
    comments = db.session.scalars(stmt).all()
    for comment in comments:
        comment.reviewed = True
    db.session.commit()
    flash('All comments published.', 'success')
    return redirect_back()


@admin_bp.route('/comment/<int:comment_id>/delete', methods=['POST'])
@login_required
def delete_comment(comment_id):
    comment = db.session.get(Comment, comment_id) or abort(404)
    db.session.delete(comment)
    db.session.commit()
    flash('Comment deleted.', 'success')
    return redirect_back()


@admin_bp.route('/category/manage')
@login_required
def manage_category():
    return render_template('admin/manage_category.html')


@admin_bp.route('/category/new', methods=['GET', 'POST'])
@login_required
def new_category():
    form = NewCategoryForm()
    if form.validate_on_submit():
        name = form.name.data
        category = Category(name=name)
        db.session.add(category)
        db.session.commit()
        flash('Category created.', 'success')
        return redirect(url_for('.manage_category'))
    return render_template('admin/new_category.html', form=form)


@admin_bp.route('/category/<int:category_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_category(category_id):
    category = db.session.get(Category, category_id) or abort(404)
    if category.id == 1:
        flash('You can not edit the default category.', 'warning')
        return redirect(url_for('blog.index'))
    form = EditCategoryForm(current_name=category.name)
    if form.validate_on_submit():
        category.name = form.name.data
        db.session.commit()
        flash('Category updated.', 'success')
        return redirect(url_for('.manage_category'))

    if request.method == 'GET':
        form.name.data = category.name
    return render_template('admin/edit_category.html', form=form)


@admin_bp.route('/category/<int:category_id>/delete', methods=['POST'])
@login_required
def delete_category(category_id):
    category = db.session.get(Category, category_id) or abort(404)
    if category.id == 1:
        flash('You can not delete the default category.', 'warning')
        return redirect(url_for('blog.index'))
    category.delete()
    flash('Category deleted.', 'success')
    return redirect(url_for('.manage_category'))


@admin_bp.route('/link/manage')
@login_required
def manage_link():
    return render_template('admin/manage_link.html')


@admin_bp.route('/link/new', methods=['GET', 'POST'])
@login_required
def new_link():
    form = LinkForm()
    if form.validate_on_submit():
        name = form.name.data
        url = form.url.data
        link = Link(name=name, url=url)
        db.session.add(link)
        db.session.commit()
        flash('Link created.', 'success')
        return redirect(url_for('.manage_link'))
    return render_template('admin/new_link.html', form=form)


@admin_bp.route('/link/<int:link_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_link(link_id):
    form = LinkForm()
    link = db.session.get(Link, link_id) or abort(404)
    if form.validate_on_submit():
        link.name = form.name.data
        link.url = form.url.data
        db.session.commit()
        flash('Link updated.', 'success')
        return redirect(url_for('.manage_link'))
    if request.method == 'GET':
        form.name.data = link.name
        form.url.data = link.url
    return render_template('admin/edit_link.html', form=form)


@admin_bp.route('/link/<int:link_id>/delete', methods=['POST'])
@login_required
def delete_link(link_id):
    link = db.session.get(Link, link_id) or abort(404)
    db.session.delete(link)
    db.session.commit()
    flash('Link deleted.', 'success')
    return redirect(url_for('.manage_link'))


@admin_bp.route('/upload', methods=['POST'])
@login_required
def upload_image():
    f = request.files.get('upload')
    if not allowed_file(f.filename):
        return upload_fail('Image only!')
    filename = random_filename(f.filename)
    f.save(current_app.config['GREYBOOK_UPLOAD_PATH'] / filename)
    url = url_for('blog.get_image', filename=filename)
    return upload_success(url, filename)

greybook/blueprints/blog.py
from flask import (
    Blueprint,
    abort,
    current_app,
    flash,
    make_response,
    redirect,
    render_template,
    request,
    send_from_directory,
    url_for,
)
from flask_login import current_user
from sqlalchemy import select
from sqlalchemy.orm import with_parent

from greybook.core.extensions import db
from greybook.emails import send_new_comment_email, send_new_reply_email
from greybook.forms import AdminCommentForm, CommentForm
from greybook.models import Category, Comment, Post
from greybook.utils import redirect_back

blog_bp = Blueprint('blog', __name__)


@blog_bp.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['GREYBOOK_POST_PER_PAGE']
    stmt = select(Post).order_by(Post.created_at.desc())
    pagination = db.paginate(stmt, page=page, per_page=per_page)
    posts = pagination.items
    return render_template('blog/index.html', pagination=pagination, posts=posts)


@blog_bp.route('/about')
def about():
    return render_template('blog/about.html')


@blog_bp.route('/category/<int:category_id>')
def show_category(category_id):
    category = db.session.get(Category, category_id) or abort(404)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['GREYBOOK_POST_PER_PAGE']
    stmt = select(Post).filter(with_parent(category, Category.posts)).order_by(Post.created_at.desc())
    pagination = db.paginate(stmt, page=page, per_page=per_page)
    posts = pagination.items
    return render_template('blog/category.html', category=category, pagination=pagination, posts=posts)


@blog_bp.route('/post/<int:post_id>', methods=['GET', 'POST'])
def show_post(post_id):
    post = db.session.get(Post, post_id) or abort(404)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['GREYBOOK_COMMENT_PER_PAGE']
    stmt = (
        select(Comment)
        .filter(with_parent(post, Post.comments))
        .filter_by(reviewed=True)
        .order_by(Comment.created_at.asc())
    )
    pagination = db.paginate(stmt, page=page, per_page=per_page)
    comments = pagination.items

    if current_user.is_authenticated:
        form = AdminCommentForm()
        form.author.data = current_user.name
        form.email.data = current_app.config['GREYBOOK_ADMIN_EMAIL']
        form.site.data = url_for('.index', _external=True)
        from_admin = True
        reviewed = True
    else:
        form = CommentForm()
        from_admin = False
        reviewed = False

    if post.can_comment and form.validate_on_submit():
        author = form.author.data
        email = form.email.data
        site = form.site.data
        body = form.body.data
        comment = Comment(
            author=author, email=email, site=site, body=body, from_admin=from_admin, post_id=post_id, reviewed=reviewed
        )
        replied_id = request.args.get('reply')
        if replied_id:
            replied_comment = db.session.get(Comment, replied_id) or abort(404)
            comment.replied = replied_comment
            send_new_reply_email(replied_comment)
        db.session.add(comment)
        db.session.commit()
        if current_user.is_authenticated:  # send message based on authentication status
            flash('Comment published.', 'success')
        else:
            flash('Thanks, your comment will be published after reviewed.', 'info')
            send_new_comment_email(post)  # send notification email to admin
        return redirect(url_for('.show_post', post_id=post_id))
    return render_template('blog/post.html', post=post, pagination=pagination, form=form, comments=comments)


@blog_bp.route('/reply/comment/<int:comment_id>')
def reply_comment(comment_id):
    comment = db.session.get(Comment, comment_id) or abort(404)
    if not comment.post.can_comment:
        flash('Comment is disabled.', 'warning')
        return redirect(url_for('.show_post', post_id=comment.post.id))
    return redirect(
        url_for('.show_post', post_id=comment.post_id, reply=comment_id, author=comment.author) + '#comment-form'
    )


@blog_bp.route('/change-theme/<theme_name>')
def change_theme(theme_name):
    if theme_name not in current_app.config['GREYBOOK_THEMES']:
        abort(400, description='Invalid theme name.')

    response = make_response(redirect_back())
    response.set_cookie('theme', theme_name, max_age=30 * 24 * 60 * 60)
    return response


@blog_bp.route('/uploads/<path:filename>')
def get_image(filename):
    return send_from_directory(current_app.config['GREYBOOK_UPLOAD_PATH'], filename)

greybook/templates/blog/_posts.html
{% if posts %}
{% for post in posts %}
<h3 class="text-primary">
  <a class="text-decoration-none" href="{{ url_for('.show_post', post_id=post.id) }}">
    {{ post.title }}
  </a>
</h3>
<p>
  {{ post.body|striptags|truncate }}
  <small>
    <a href="{{ url_for('.show_post', post_id=post.id) }}">Read More</a>
  </small>
</p>
<small>
  Comments:
  <a href="{{ url_for('.show_post', post_id=post.id) }}#comments">
    {{ post.reviewed_comments_count }}
  </a>&nbsp;&nbsp;
  Category:
  <a href="{{ url_for('.show_category', category_id=post.category.id) }}">
    {{ post.category.name }}
  </a>
  <span class="float-end dayjs">{{ post.created_at }}</span>
</small>
{% if not loop.last %}
<hr>
{% endif %}
{% endfor %}
{% else %}
<div class="tip">
  <h5>No posts yet.</h5>
  {% if current_user.is_authenticated %}
  <a href="{{ url_for('admin.new_post') }}">Write Now</a>
  {% endif %}
</div>
{% endif %}

greybook/templates/blog/_sidebar.html
{% if links %}
<div class="card mb-3">
  <div class="card-header">Links</div>
  <ul class="list-group list-group-flush">
    {% for link in links %}
    <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
      <a class="text-decoration-none" href="{{ link.url }}" target="_blank">
        {{ link.name }}
      </a>
    </li>
    {% endfor %}
  </ul>
</div>
{% endif %}
{% if categories %}
<div class="card mb-3">
  <div class="card-header">Categories</div>
  <ul class="list-group list-group-flush">
    {% for category in categories %}
    <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
      <a class="text-decoration-none"
          href="{{ url_for('blog.show_category', category_id=category.id) }}">
        {{ category.name }}
      </a>
      <span class="badge text-bg-primary rounded-pill"> {{ category.posts|length }}</span>
    </li>
    {% endfor %}
  </ul>
</div>
{% endif %}
<div class="dropdown">
  <button class="btn btn-light dropdown-toggle btn-sm" type="button"
      id="dropdownMenuButton" data-bs-toggle="dropdown"
      aria-haspopup="true" aria-expanded="false">
    Change Theme
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    {% for theme_name, display_name in config.GREYBOOK_THEMES.items() %}
    <li>
      <a class="dropdown-item"
          href="{{ url_for('blog.change_theme', theme_name=theme_name, next=request.full_path) }}">
        {{ display_name }}
      </a>
    </li>
    {% endfor %}
  </ul>
</div>

greybook/templates/blog/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock %}

{% block content %}
<div class="page-header">
  <h1>About</h1>
</div>
<div class="row">
  <div class="col-sm-8">
    {{ admin.about|safe }}
  </div>
  <div class="col-sm-4 sidebar">
    {% include 'blog/_sidebar.html' %}
  </div>
</div>
{% endblock %}

greybook/templates/blog/category.html
{% extends 'base.html' %}
{% from 'bootstrap5/pagination.html' import render_pagination %}

{% block title %}{{ category.name }}{% endblock %}

{% block content %}
<div class="page-header">
  <h1>Category: {{ category.name }}</h1>
  <p class="text-muted">
    {{ category.posts|length }} posts
  </p>
</div>
<div class="row">
  <div class="col-sm-8">
    {% include "blog/_posts.html" %}
    <div class="page-footer">
      {{ render_pagination(pagination) }}
    </div>
  </div>
  <div class="col-sm-4 sidebar">
    {% include 'blog/_sidebar.html' %}
  </div>
</div>
{% endblock %}

greybook/templates/blog/index.html
{% extends 'base.html' %}
{% from 'bootstrap5/pagination.html' import render_pager %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="page-header">
  <h1 class="display-3">{{ admin.blog_title|default('Blog Title') }}</h1>
  <h4 class="text-muted">&nbsp;{{ admin.blog_sub_title|default('Blog Subtitle') }}</h4>
</div>
<div class="row">
  <div class="col-sm-8">
    {% include 'blog/_posts.html' %}
    {% if posts %}
    <div class="page-footer">
      {{ render_pager(pagination) }}
    </div>
    {% endif %}
  </div>
  <div class="col-sm-4 sidebar">
    {% include 'blog/_sidebar.html' %}
  </div>
</div>
{% endblock %}

greybook/templates/blog/post.html
{% extends 'base.html' %}
{% from 'bootstrap5/form.html' import render_form %}
{% from 'bootstrap5/pagination.html' import render_pagination %}
{% from 'macros.html' import render_inline_form %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<div class="page-header">
  <h1>{{ post.title }}
    <span class="float-end">
      {% if current_user.is_authenticated %}
      <a class="btn btn-outline-info btn-sm"
          href="{{ url_for('admin.edit_post', post_id=post.id) }}">
        Edit
      </a>
      {{ render_inline_form(
        action=url_for('admin.delete_post', post_id=post.id, next=url_for('blog.index')),
        button_style='outline-danger',
        button_text='Delete',
      ) }}
      {% endif %}
    </span>
  </h1>
</div>
<div class="row">
  <div class="col-sm-8">
    <div class="post-body">{{ post.body|safe }}</div>
    <small>
      Created at <u class="dayjs">{{ post.created_at }}</u>,
      {% if post.updated_at %}last updated at <u class="dayjs">{{ post.updated_at }}</u>,{% endif %}
      belongs to the
      <a href="{{ url_for('.show_category', category_id=post.category.id) }}">
        {{ post.category.name }}
      </a> category.
    </small>
    <hr>
    <button type="button" class="btn btn-primary btn-sm" data-bs-toggle="modal"
        data-bs-target=".postLinkModal">
      Share
    </button>
    <div class="modal fade postLinkModal" tabindex="-1" role="dialog"
        aria-labelledby="mySmallModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Permalink</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal"
                aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <div class="form-group">
              <input type="text" class="form-control"
                value="{{ url_for('.show_post', post_id=post.id, _external=True) }}" readonly>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="comments" id="comments">
      <h3>{{ pagination.total }} Comments
        <small style="font-size: small;">
          <a href="{{ url_for('.show_post', post_id=post.id, page=pagination.pages or 1) }}#comments">
            latest
          </a>
        </small>
        {% if current_user.is_authenticated %}
        <div class="float-end">
          {{ render_inline_form(
            action=url_for('admin.set_comment', post_id=post.id, next=request.full_path),
            button_style='outline-warning' if post.can_comment else 'outline-success',
            button_text='Disable Comment' if post.can_comment else 'Enable Comment',
            confirm=None,
          ) }}
        </div>
        {% endif %}
      </h3>
      {% if comments %}
      <ul class="list-group">
        {% for comment in comments %}
        <li class="list-group-item list-group-item-action flex-column">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1 mt-2">
              <a class="text-decoration-none"
                  href="{% if comment.site %}{{ comment.site }}{% else %}#{% endif %}" target="_blank">
                {% if comment.from_admin %}{{ admin.name }}{% else %}{{ comment.author }}{% endif %}
              </a>
              {% if comment.from_admin %}<span class="badge rounded-pill text-bg-secondary">Author</span>{% endif %}
            </h5>
            <small class="dayjs-tooltip" data-bs-toggle="tooltip" data-bs-placement="top"
                data-bs-delay="500" data-timestamp="{{ comment.created_at }}">
              <span class="dayjs-from-now">{{ comment.created_at }}</span>
            </small>
          </div>
          {% if comment.replied %}
          <p class="alert alert-primary reply-body">
            {{ comment.replied.author }}:<br>
            {{ comment.replied.body }}
          </p>
          {% endif %}
          <p class="mb-1">{{ comment.body }}</p>
          <div class="float-end">
            <a class="btn btn-light btn-sm"
                href="{{ url_for('.reply_comment', comment_id=comment.id) }}">Reply</a>
            {% if current_user.is_authenticated %}
            <a class="btn btn-outline-info btn-sm" href="mailto:{{ comment.email }}">Email</a>
            {{ render_inline_form(
              action=url_for('admin.delete_comment', comment_id=comment.id, next=request.full_path),
              button_style='outline-danger',
              button_text='Delete',
            ) }}
            {% endif %}
          </div>
        </li>
        {% endfor %}
      </ul>
      {% else %}
      <div class="tip">
        <h5>No comments.</h5>
      </div>
      {% endif %}
    </div>
    {% if comments %}
    {{ render_pagination(pagination, fragment='#comments') }}
    {% endif %}
    {% if request.args.get('reply') %}
    <div class="alert alert-primary">
      Reply to <strong>{{ request.args.get('author') }}</strong>:
      <a class="float-end" href="{{ url_for('.show_post', post_id=post.id) }}">Cancel</a>
    </div>
    {% endif %}
    {% if post.can_comment %}
    <div id="comment-form">
      {{ render_form(form, action=request.full_path) }}
    </div>
    {% else %}
    <div class="tip">
      <h5>Comment disabled.</h5>
    </div>
    {% endif %}
  </div>
  <div class="col-sm-4 sidebar">
    {% include 'blog/_sidebar.html' %}
  </div>
</div>
{% endblock %}